In [20]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder
import pickle

In [21]:
data=pd.read_csv('Churn_Modelling.csv')
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [22]:
#Preprocess the data
data=data.drop(['RowNumber', 'CustomerId', 'Surname'], axis=1)

In [23]:
#Encode categorical variables
label_encoder_gender= LabelEncoder()
data['Gender']= label_encoder_gender.fit_transform(data['Gender'])

In [24]:
#One-hot encode the 'Geography' column
onehot_encoder_geo= OneHotEncoder(handle_unknown='ignore')
geo_encoded=onehot_encoder_geo.fit_transform(data[['Geography']]).toarray()
geo_encoded_df=pd.DataFrame(geo_encoded, columns=onehot_encoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [25]:
#Combine the one-hot encoded 'Geography' columns with the original dataset
data=pd.concat([data.drop('Geography', axis=1), geo_encoded_df], axis=1)
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [26]:
#Split the dataset into features and target variable
X = data.drop('EstimatedSalary', axis=1)
y = data['EstimatedSalary']

In [27]:
#Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [41]:
#Save the encosers and scalars for future use
with open ('label_encoder_gender.pkl', 'wb') as file:
    pickle.dump(label_encoder_gender, file)


with open ('onehot_encoder_geo.pkl', 'wb') as file:
    pickle.dump(onehot_encoder_geo, file)

scaler=StandardScaler()
X_train = scaler.fit_transform(X_train)

# Transform test data
X_test = scaler.transform(X_test)
with open ('scaler.pkl', 'wb') as file:
    pickle.dump(scaler, file)

In [42]:
### ANN Regression problem statement

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [43]:
#Build the ANN model

model= Sequential([
    Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
    Dense(32, activation='relu'),
    Dense(1)
])

#Compile the model
model.compile(optimizer='adam', loss='mean_absolute_error', metrics=['mae'])

model.summary()

d:\Swati\AIBasics\annclassification\myenv\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_9 (Dense)                 │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_10 (Dense)                │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_11 (Dense)                │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [44]:
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime

#Set up TensorBoard logging
log_dir = "regressionlogs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback = TensorBoard(log_dir=log_dir, histogram_freq=1)

In [45]:
#Early stopping to prevent overfitting
early_stopping = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)

In [46]:
#Train the model
history = model.fit(
    X_train, y_train, 
    epochs=100, 
    validation_data=(X_test, y_test), 
    callbacks=[tensorboard_callback, early_stopping]
)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 100387.4297 - mae: 100387.4297 - val_loss: 98558.9688 - val_mae: 98558.9688
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 99810.5938 - mae: 99810.5938 - val_loss: 97408.6875 - val_mae: 97408.6875
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 97809.0156 - mae: 97809.0156 - val_loss: 94462.9922 - val_mae: 94462.9922
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 93809.6562 - mae: 93809.6562 - val_loss: 89409.3281 - val_mae: 89409.3281
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 87793.7656 - mae: 87793.7656 - val_loss: 82562.2422 - val_mae: 82562.2422
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 80255.7500 - mae: 80255.7500 - val_loss: 74711.9375 - val_mae: 74711.9375
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 72198.0234 - mae: 72198.0234 - val_loss: 67106.7500 - val_mae: 67106.7500
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 64694.4805 - mae: 64694.4805 - val_loss: 60609.9141 - val_mae: 60609.9141
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 58680.6719 - mae: 58680.6719 - val_loss: 55806.3984 - val_mae: 55806.3984
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 54654.9688 - mae: 54654.9688 - val_loss: 52950.9961 - val_mae: 52950.9961
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 52346.7305 - mae: 52346.7305 - val_loss: 51503.6875 - val_mae: 51503.6875
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 51209.0391 - mae: 51209.0391 - val_loss: 50921.3906 - val_mae: 50921.3906
Epoch 13/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50691.0312 - mae: 50691.0312 - val_loss: 50722.6094 - val_mae: 50722.6094
Epoch 14/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 50447.8906 - mae: 50447.8906 - val_loss: 50648.7812 - val_mae: 50648.7812
Epoch 15/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50323.6133 - mae: 50323.6133 - val_loss: 50607.1445 - val_mae: 50607.1445
Epoch 16/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50233.2109 - mae: 50233.2109 - val_loss: 50572.1016 - val_mae: 50572.1016
Epoch 17/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50170.9336 - mae: 50170.9336 - val_loss: 50550.0586 - val_mae: 50550.0586
Epoch 18/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50122.8828 - mae: 50122.8828 - val_loss: 50524.1367 - val_mae: 50524.1367
Epoch 19/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50079.2461 - mae: 50079.2461 - val_loss: 50508.7188 - val_mae: 50508.7188
Epoch 20/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50043.5977 - mae: 50043.5977 - val_loss: 50492.1875 - val_mae: 50492.1875
Epoch 21/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50007.4219 - mae: 50007.4219 - val_loss: 50482.8398 - val_mae: 50482.8398
Epoch 22/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49975.1562 - mae: 49975.1562 - val_loss: 50464.1289 - val_mae: 50464.1289
Epoch 23/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49946.4688 - mae: 49946.4688 - val_loss: 50450.2148 - val_mae: 50450.2148
Epoch 24/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49921.1875 - mae: 49921.1875 - val_loss: 50439.7188 - val_mae: 50439.7188
Epoch 25/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49895.6094 - mae: 49895.6094 - val_loss: 50433.5977 - val_mae: 50433.5977
Epoch 26/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49871.6328 - mae: 49871.6328 - val_loss: 50418.8711 - val_mae: 50418.8711
Epoch 27/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49852.8008 - mae: 49852.8008 - val_loss: 50416.1992 - val_mae: 50416.1992
Epoch 28/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49829.5391 - mae: 49829.5391 - val_loss: 50401.6016 - val_mae: 50401.6016
Epoch 29/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49815.4609 - mae: 49815.4609 - val_loss: 50392.2148 - val_mae: 50392.2148
Epoch 30/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49797.4961 - mae: 49797.4961 - val_loss: 50379.7070 - val_mae: 50379.7070
Epoch 31/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49777.3750 - mae: 49777.3750 - val_loss: 50378.7852 - val_mae: 50378.7852
Epoch 32/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49763.1914 - mae: 49763.1914 - val_loss: 50366.4688 - val_mae: 50366.4688
Epoch 33/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49748.6953 - mae: 49748.6953 - val_loss: 50365.9531 - val_mae: 50365.9531
Epoch 34/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49732.6914 - mae: 49732.6914 - val_loss: 50363.2422 - val_mae: 50363.2422
Epoch 35/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49721.1328 - mae: 49721.1328 - val_loss: 50355.5781 - val_mae: 50355.5781
Epoch 36/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49706.3555 - mae: 49706.3555 - val_loss: 50352.4375 - val_mae: 50352.4375
Epoch 37/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49693.9219 - mae: 49693.9219 - val_loss: 50345.8750 - val_mae: 50345.8750
Epoch 38/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49681.6016 - mae: 49681.6016 - val_loss: 50338.5312 - val_mae: 50338.5312
Epoch 39/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49673.3555 - mae: 49673.3555 - val_loss: 50335.1602 - val_mae: 50335.1602
Epoch 40/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49663.7070 - mae: 49663.7070 - val_loss: 50332.1719 - val_mae: 50332.1719
Epoch 41/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49653.9609 - mae: 49653.9609 - val_loss: 50330.7383 - val_mae: 50330.7383
Epoch 42/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49643.4141 - mae: 49643.4141 - val_loss: 50333.9531 - val_mae: 50333.9531
Epoch 43/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49632.8867 - mae: 49632.8867 - val_loss: 50329.2188 - val_mae: 50329.2188
Epoch 44/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49622.5938 - mae: 49622.5938 - val_loss: 50328.5703 - val_mae: 50328.5703
Epoch 45/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49614.6016 - mae: 49614.6016 - val_loss: 50325.8945 - val_mae: 50325.8945
Epoch 46/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49607.9727 - mae: 49607.9727 - val_loss: 50329.8086 - val_mae: 50329.8086
Epoch 47/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49595.0000 - mae: 49595.0000 - val_loss: 50320.8125 - val_mae: 50320.8125
Epoch 48/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49590.3906 - mae: 49590.3906 - val_loss: 50320.1406 - val_mae: 50320.1406
Epoch 49/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49581.9648 - mae: 49581.9648 - val_loss: 50321.2969 - val_mae: 50321.2969
Epoch 50/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49571.3125 - mae: 49571.3125 - val_loss: 50324.3398 - val_mae: 50324.3398
Epoch 51/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49569.6680 - mae: 49569.6680 - val_loss: 50317.2930 - val_mae: 50317.2930
Epoch 52/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49560.3242 - mae: 49560.3242 - val_loss: 50323.5234 - val_mae: 50323.5234
Epoch 53/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49553.5469 - mae: 49553.5469 - val_loss: 50321.8555 - val_mae: 50321.8555
Epoch 54/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49546.0234 - mae: 49546.0234 - val_loss: 50329.6094 - val_mae: 50329.6094
Epoch 55/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49540.1094 - mae: 49540.1094 - val_loss: 50325.9219 - val_mae: 50325.9219
Epoch 56/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49535.5312 - mae: 49535.5312 - val_loss: 50325.8398 - val_mae: 50325.8398
Epoch 57/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49533.0273 - mae: 49533.0273 - val_loss: 50328.4648 - val_mae: 50328.4648
Epoch 58/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49523.3750 - mae: 49523.3750 - val_loss: 50326.7422 - val_mae: 50326.7422
Epoch 59/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49517.5547 - mae: 49517.5547 - val_loss: 50329.2188 - val_mae: 50329.2188
Epoch 60/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49514.1719 - mae: 49514.1719 - val_loss: 50334.0859 - val_mae: 50334.0859
Epoch 61/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49506.6445 - mae: 49506.6445 - val_loss: 50330.8359 - val_mae: 50330.8359

In [47]:
%load_ext tensorboard

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard

In [48]:
%tensorboard --logdir regressionlogs/fit

Reusing TensorBoard on port 6006 (pid 22332), started 0:22:44 ago. (Use '!kill 22332' to kill it.)

In [49]:
#Evaluate model on the test data
test_loss, test_mae = model.evaluate(X_test, y_test)
print(f"Test Loss: {test_loss}, Test MAE: {test_mae}")

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 50317.2930 - mae: 50317.2930
Test Loss: 50317.29296875, Test MAE: 50317.29296875

In [50]:
model.save('regression_model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.